framework:
  build: .
  external_links:
    - mesoslocal_zookeeper_1:zk
    - mesoslocal_mesosmaster_1:mesosmaster
    - mesoslocal_mesosslave_1:mesosslave
  entrypoint: /bin/bash
  command: -c "while true; do echo 'Hit CTRL+C'; sleep 10; done"
  ports:
    - "4000:4000"


